default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: isma_development
  username: isma
  password: <%= ENV['ISMA_DATABASE_PASSWORD'] %>
  host: <%= ENV['ISMA_DATABASE_HOST'] %>

test:
  <<: *default
  database: isma_test

production:
  <<: *default
  database: isma_production
  username: isma
  password: <%= ENV['ISMA_DATABASE_PASSWORD'] %>
  host: <%= ENV['ISMA_DATABASE_HOST'] %>
